first commit

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -45,16 +45,16 @@ jobs:
           dataform install
           dataform compile --json > output.json
 
-      - name: Locate and Copy Credential File
-        run: |
-          CREDENTIAL_FILE=$(ls $GITHUB_WORKSPACE | grep -E '.*\.json$')
-          if [ -z "$CREDENTIAL_FILE" ]; then
-            echo "Error: Credential file not found"
-            exit 1
-          fi
-          echo "Credential file found: $CREDENTIAL_FILE"
-          mv "$GITHUB_WORKSPACE/$CREDENTIAL_FILE" "$GITHUB_WORKSPACE/.df-credentials.json"
-          cp "$GITHUB_WORKSPACE/.df-credentials.json" demo-project/
+      # - name: Locate and Copy Credential File
+      #   run: |
+      #     CREDENTIAL_FILE=$(ls $GITHUB_WORKSPACE | grep -E '.*\.json$')
+      #     if [ -z "$CREDENTIAL_FILE" ]; then
+      #       echo "Error: Credential file not found"
+      #       exit 1
+      #     fi
+      #     echo "Credential file found: $CREDENTIAL_FILE"
+      #     mv "$GITHUB_WORKSPACE/$CREDENTIAL_FILE" "$GITHUB_WORKSPACE/.df-credentials.json"
+      #     cp "$GITHUB_WORKSPACE/.df-credentials.json" demo-project/
     
       - name: Run dataform2looker taking output.json as input
         run: |
