first commit

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -38,11 +38,16 @@ jobs:
           workload_identity_provider: 'projects/509432560350/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
           audience: audience-default
 
-      - name: Find the Google Cloud credential file
+      - name: Locate and Set Credential File
         run: |
-          CREDENTIAL_FILE=$(ls $GITHUB_WORKSPACE | grep -E '.*json$')
+          CREDENTIAL_FILE=$(ls $GITHUB_WORKSPACE | grep -E '.*\.json$')
+          if [ -z "$CREDENTIAL_FILE" ]; then
+            echo "Error: Credential file not found"
+            exit 1
+          fi
+          echo "Credential file found: $CREDENTIAL_FILE"
           echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/$CREDENTIAL_FILE" >> $GITHUB_ENV
-      
+        
       - name: Clone dataform2looker-demo and compile dataform json file
         run: |
           git clone ${{env.dataform-repo}} demo-project
@@ -51,6 +56,8 @@ jobs:
           dataform compile --json > output.json
     
       - name: Run dataform2looker taking output.json as input
+        env:
+          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
         run: |
          cd demo-project
          ls
